# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "linux" do |linux|
      linux.vm.box = "hashicorp/bionic64"

      linux.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--macaddress1", "5CA1AB1E0001" ]
      end
  end

  config.vm.define "macos" do |macos|
      macos.vm.box = "ngyewch/macos-high-sierra"

      macos.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--macaddress1", "5CA1AB1E0001" ]
      end
  end
end
