# This is a basic workflow to help you get started with Actions

name: CreateRunner

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  start_testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Don't run if we ask to skip CI
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Creates the new VM
      - name: Invoke creation hook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: '{ "ghcontrol": "create", "server" : "linux" }'
      # Starts the job on the local runner
      - name: Invoke workflow with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: localRun
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "test": "custom"}'
