name: localRun

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      test:
        description: 'What test to perform'
        required: false
        default: 'all'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: linux_matlab

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo "Tests: ${{ github.event.inputs.test }}"

      # Runs a set of commands using the MATLAB shell
      - name: Run a multi-line script
        run: |
          matlab -nosplash -nodesktop -nojvm -r "disp('Hello World'); exit"
      # Destroys self
      - name: Invoke workflow with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: DestroyRunner
          token: ${{ secrets.PERSONAL_TOKEN }}